package com.tjpu.dao;

import com.tjpu.pojo.Sysrole;
import com.tjpu.pojo.SysroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int countByExample(SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int deleteByExample(SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int insert(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int insertSelective(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    List<Sysrole> selectByExample(SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    Sysrole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") Sysrole record, @Param("example") SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int updateByExample(@Param("record") Sysrole record, @Param("example") SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int updateByPrimaryKeySelective(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    int updateByPrimaryKey(Sysrole record);
}