package com.tjpu.pojo;

public class Sysrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.id
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.role
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.descrip
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    private String descrip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.id
     *
     * @return the value of sysrole.id
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.id
     *
     * @param id the value for sysrole.id
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.role
     *
     * @return the value of sysrole.role
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.role
     *
     * @param role the value for sysrole.role
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.descrip
     *
     * @return the value of sysrole.descrip
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    public String getDescrip() {
        return descrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.descrip
     *
     * @param descrip the value for sysrole.descrip
     *
     * @mbggenerated Fri Dec 30 12:36:16 CST 2016
     */
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }
}